---
- name: Make sure the komf container is created and running
  docker_container:
    image: sndxr/komf:latest
    name: komf
    networks:
      - name: proxy
    dns_servers:
      - "{{ server_ip }}"  # Pi-hole server
    ports:
      - "8099:8085"
    pull: yes
    state: 'started'
    recreate: yes
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.komf.entrypoints: "http"
      traefik.http.routers.komf.rule: "Host(`komf.{{ domain }}`)"
      traefik.http.middlewares.komf-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.komf.middlewares: "komf-https-redirect"
      traefik.http.routers.komf-secure.entrypoints: "https"
      traefik.http.routers.komf-secure.rule: "Host(`komf.{{ domain }}`)"
      traefik.http.routers.komf-secure.tls: "true"
      traefik.http.routers.komf-secure.service: "komf"
      traefik.http.services.komf.loadbalancer.server.port: "8085"
    volumes:
      - "{{ config_root }}/komf_config:/config"
      - "{{ data_root }}/media/comics:/comics"
      - "{{ data_root }}/media/kavita:/kavita"
    restart_policy: unless-stopped
